### ISSUE TITLE
As a user I can follow the presented steps that guide me how to use the platform so that I will know how to use the platform.

### ISSUE THREAD

**Issue by denisapredescu** [denisapredescu/Teach-Us#10]

**Comment by postolache-andreea-miruna** [comment]
The steps have to be different based on user role.

**Comment by alexion2001** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/81268e2a-0d4f-4697-be73-3af54d36b48d)
Nu e deja chestia asta ????

**Comment by alexion2001** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/305a48e4-e57a-4140-9538-18cb599e2564)


![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/c078cc86-7b0a-43e7-a026-89ce7d8a822a)
