### ISSUE TITLE
As a user I can sort the teachers via name and rating points so that I can view them in a suitable order.

### ISSUE THREAD

**Issue by denisapredescu** [denisapredescu/Teach-Us#12]
ACCEPTANCE CRITERIA:
- Sorting options:
>- ascending and descending via name 
>- ascending and descending via rating points
- By pressing a sorting method, the list of teachers will change his elements order
- Just an unregistered user and a student can see this list of teachers

**Comment by postolache-andreea-miruna** [comment]
duplicat

**Comment by alexion2001** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/0d5b2df8-54f2-484c-b619-8f7263551b0f)
