### ISSUE TITLE
As a teacher I can assign homework  to my students so that I can reinforce their learning and keep them organize

### ISSUE THREAD

**Issue by Talida-M** [denisapredescu/Teach-Us#21]
ACCEPTANCE CRITERIA:
- The teacher can complete a form with details about the tasks.
- The form will contain the assessment, the deadline information.
- The student can see his assigned homework. 
- The student can see his/her assessments in a interface that looks like a book.
- The student can check it if it's done.

**Comment by postolache-andreea-miruna** [comment]
- The student can see his assigned homework 
- The student can check it if it's done
