### ISSUE TITLE
issue_about_us

### ISSUE THREAD

**Issue by postolache-andreea-miruna** [denisapredescu/Teach-Us#44]
<img width="666" alt="image" src="https://github.com/denisapredescu/Teach-Us/assets/79594745/5d21142c-79c5-438e-9938-14da7c0c08c5">
nu imi apare textul

_Originally posted by @postolache-andreea-miruna in https://github.com/denisapredescu/Teach-Us/issues/9#issuecomment-1828503344_

**Comment by Talida-M** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/75331740/71df50e8-1c91-4233-9d72-bfca592a903c)
text added
