### ISSUE TITLE
issue_student_guid_steps

### ISSUE THREAD

**Issue by postolache-andreea-miruna** [denisapredescu/Teach-Us#47]
"Edit profile", "Search teacher" si Learn" nu duc la paginile corespunzatoare

<img width="356" alt="image" src="https://github.com/denisapredescu/Teach-Us/assets/79594745/c92979a2-dc79-4784-92fb-85aeaa780240">

Edit profile trebuie sa faca trimitere la pagina de Settings din profilul utilizatorului
Search Teacher trebuie sa faca trimitere la pagina de Matching
Learn trebuie sa faca trimitere la pagina Watch Videos din profilul utilizatorului

**Comment by denisapredescu** [comment]
Sa verifici te rog ca si utilizatorul neinregistrat si studentul sa aiba toti acei pasi cu redirect catre pagini @alexion2001
