### ISSUE TITLE
As a student I can access the top teachers list so I will select the best choice.

### ISSUE THREAD

**Issue by denisapredescu** [denisapredescu/Teach-Us#7]

**Comment by postolache-andreea-miruna** [comment]
- on home page will be displayed the top 3 teachers 
- the top 3 teachers will be displayed as a podium
- it will be visible for everyone

**Comment by alexion2001** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/27d95054-3dac-479a-ba09-e57599127632)

**Comment by alexion2001** [comment]
![image](https://github.com/denisapredescu/Teach-Us/assets/96074975/7f346de6-dcea-41d5-bcbc-2791d94961ff)

**Comment by postolache-andreea-miruna** [comment]
@alexion2001 trebuie sa ai posibilitatea sa alegi undeva materia pe baza careia sa faci topul
